repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-yaml
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.31.1
    hooks:
      - id: markdownlint
  - repo: https://github.com/tcort/markdown-link-check
    rev: v3.10.2
    hooks:
      - id: markdown-link-check
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.6.2
    hooks:
      - id: prettier
        types_or: [yaml, markdown]
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.25.0
    hooks:
      - id: commitizen
        stages: [commit-msg]
